
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmzntarliewjyuzirqiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtem50YXJsaWV3anl1emlycWl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM5NTI2ODQsImV4cCI6MjA1OTUyODY4NH0.Bw8g1oARoD9Xidu-806DFZO05uw2pvMWZ2ZDUEdgtQU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
